Selenium test
Knarik-Dabaghyan/project1 pull request #5
Opened 2021-03-22 11:45 UTC by Knarik-Dabaghyan

2021-03-22 17:07 UTC, chandranik90 commented
driver file should be kept in resources folder

2021-03-22 17:20 UTC, chandranik90 requested changes

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +public class seleniumTest {
Please follow the naming convention. Class name should start with upper-case

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +    private WebDriver driver;
There is just 1 method using this field. So, it could be simply converted to a local variable.

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +        driver.findElement(By.xpath("//a[@href='/downloads']")).click();
There are 5 elements found by this locator. Please write such one, which would find a unique element in the DOM

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +        WebElement versionElement = driver.findElement(By.xpath("//a[@href='https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar']"));
Again, there are 2 elements found by this locator. You should write such a locator, which will find just 1 unique.
Also, you have to use somehow the `Latest stable version` text. Otherwise, your test will be flaky

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +        WebElement elem = driver.findElement(By.xpath("//input[@name='search']"));
Use full and meaningful names for variables, like `searchEditBox` instead of just `elem`

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +        list.add("//a[@href='https://www.seleniumhq.org/']");
No need to explicitly use all the possible links of the page. Those links can be changed anytime, even when you run the same test twice during 5 minutes. You should use some generic locator in order to find all the links on the page, then get their texts and compare with your expected text.

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +        boolean b = false;
Here as well. Please use meaningful name for the variable

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +            String LinkText = driver.findElement(By.xpath(list.get(i))).getText().toLowerCase();
Variable name should start with lower-case

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +            if (LinkText.contains(expectedSearch)) {
`contains` should not be used here. You need to check equality instead.

2021-03-22 17:20 UTC, chandranik90 commented on src/test/java/seleniumTest.java
> +        Assert.assertTrue(b);
Please use an assertion message in order to make the final test result more readable. This is especially useful, when test fails in some reason

2021-03-22 20:22 UTC, Knarik-Dabaghyan commented on src/test/java/seleniumTest.java
> +public class seleniumTest {
Changes are in new file SeleniumTest

2021-03-23 17:20 UTC, chandranik90 requested changes

2021-03-23 17:20 UTC, chandranik90 commented on src/test/java/SeleniumTest.java
> +        WebElement versionElement = driver.findElement(By.xpath("//p[text()='Latest stable version ']//a[@href='https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.
Your locator still uses link to the jar. It should be an abstract one. It should just find the actual latest version.

2021-03-23 17:20 UTC, chandranik90 commented on src/test/java/SeleniumTest.java
> +            System.out.println("Find link that contains 'selenium webdriver'");
Redundant `if-else` statement. Could be easily replaced by simple assertion message below

2021-03-23 17:20 UTC, chandranik90 commented on src/test/java/SeleniumTest.java
> +        list.add("//div[@class='gs-title']//a[@href='https://www.seleniumhq.org/']");
The previous comment is not fixed. You still use all the links explicitely

2021-03-25 16:51 UTC, merged