Add Sixpm_comTest project
Knarik-Dabaghyan/project1 pull request #7
Opened 2021-03-28 17:46 UTC by Knarik-Dabaghyan

2021-03-28 18:24 UTC, David91 requested changes
Please at first divide your test into pre test and post test actions.

2021-03-28 18:43 UTC, chandranik90 requested changes

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +public class Sixpm_comTest {
Don't use `_`-s. Follow the naming convention for class names and method names

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[text()='Aviators']"))).click();
Visibility doesn't guarantee clickability. If you are going to click on an element, use `elementToBeClickable` method

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[text()='Add to Shopping Bag']"))).click();
The same is here

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        WebElement productAmount = driver.findElement(By.xpath("//em[@class='yh-z Bh-z']"));
Maybe product price instead of amount?

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        String amountOfProduct = productAmount.getText().replaceAll("[^\\,0-9]", "").replaceAll(",", ".");
`,` is simple character for RegExp template. You don't need to use a backslash in order to mark that as a character.
By the way, I see `.` in the price and not `,`.
And why are you using 2 `replaceAll`-s?

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        String actualModel = driver.findElement(By.xpath("//span[@class='Xk-z']")).getText();
After clicking on My Bag, it's necessary to use explicit wait. Your test may fail due to not finding the element right after clicking the My Bag

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        String amountProd = amount.getText().replaceAll("[^\\,0-9]", "").replaceAll(",", ".");
Use meaningful names for variables.

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        Assert.assertEquals(expectedModel, actualModel, "expected model not equal actual model");
Start the assert message by upper case

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//option[text()='Remove']"))).click();
It's better to wait after clicking on Remove. Otherwise, the driver may be closed very quick and the deletion process can be incomplete

2021-03-28 18:43 UTC, chandranik90 commented on src/test/java/Sixpm_comTest.java
> +        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
There was nothing about pre and post conditions implementation in the task. However, I would suggest using them for initializing and quitting the driver respectively.

2021-03-30 14:43 UTC, David91 approved these changes

2021-03-30 14:43 UTC, David91 commented on src/test/java/SixpmcomTest.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@class='NB-z']")));
These steps are post test actions, as they come after assertions and aren't related to tested functional

2021-04-01 08:11 UTC, merged