Add AmazonComTest project with Page Factory
Knarik-Dabaghyan/project1 pull request #9
Opened 2021-04-03 17:22 UTC by Knarik-Dabaghyan

2021-04-04 07:04 UTC, David91 requested changes

2021-04-04 07:04 UTC, David91 commented on src/main/java/pages/BooksPage.java
>      }
1. This method's name doesn't match with what it does actually.
2. Why to have such a method, when sendKeys() method focuses on input field and writes there without requiring explicitly click on it before it starts writing ?

2021-04-04 18:46 UTC, chandranik90 requested changes

2021-04-04 18:46 UTC, chandranik90 commented on src/main/java/pages/AuthorBooksPage.java
>      private WebDriver driver;
You have `driver` field in all page classes. However, those are never being used.

2021-04-04 18:46 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
>      public String getElementText() {
Method name doesn't say anything. Please rename it to more meaningful one

2021-04-04 18:46 UTC, chandranik90 commented on src/test/java/AmazonComTest.java
>          Assert.assertEquals(textActual, textExpected, "Expected text not equal actual text");
Bad style of assertion message. It's too abstract. Specify what exactly was compared and what was wrong.

2021-04-04 18:46 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
>      public void clickOnFilterElement() {
The name of this method doesn't represent what it exactly does. Reading the method's name, I would think that it is intended just for clicking on the filter. However, it actually selects a particular item from the filter. So, it should be named correctly

2021-04-04 18:46 UTC, chandranik90 commented on src/main/java/pages/AuthorBooksPage.java
>      public boolean isContainText(String expectedSearch) {
Several points here:
1. This method is named like just a checker of some text. However, it both checks and performs some action (clicking). So, either the name should be changed respectively, or the method should be split into 2 separate methods (checking and clicking)
2. `Is contains` is not a right style for naming of such methods. Use the `is` prefix in case of the second part is a boolean condition or a adjective (e.g: `isTrue`, 'isVisible`). But never with a verb. So, in this case you could name the method just `containsText`

2021-04-04 18:46 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +        wait.until(ExpectedConditions.visibilityOf(lowToHighElement));
Before clicking always try to use explicit wait for clickability instead of visibility check.

2021-04-04 18:46 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
Condition is not correct. `isLowToHigh` should be true only If all the items on the list match the condition.

2021-04-11 16:34 UTC, chandranik90 requested changes
There are 2 compile errors. One in `AmazonComTest` class, and the second one - in `SixpmcomTest`.

2021-04-11 16:34 UTC, chandranik90 commented on src/main/java/pages/AuthorBooksPage.java
> +    public boolean ContainsTextAndClick(String expectedSearch) {
Start the method name by lowercase

2021-04-11 16:34 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +            break;
`break` is out of both `if` and else `blocks`. So, the logic of your looping condition is incorrect, since the loop will be stopped after the first iteration in any case.

2021-04-11 16:34 UTC, chandranik90 commented on src/main/java/pages/AuthorPage.java
> +    public void clickOnElements() {
Which elements? Choose meaningful names. The name of the method should give a concrete definition of the behavior. It's impossible to understand the exact behavior of the method by reading the name of this method.

2021-04-11 16:34 UTC, chandranik90 commented on src/test/java/AmazonComTest.java
> +                    new FileReader("src/test/resources/parameter.json")));
Seems, you forgot to add the resources folder to the repository.
Instead, you have added an extra pom.xml file into the test directory, which is not correct.

2021-04-11 16:34 UTC, chandranik90 commented on src/test/java/AmazonComTest.java
> +    static class DataGenerator {
Is there a specific reason for using nested static class here?

2021-04-20 14:17 UTC, merged